name: GitHub release patch version

on:
  workflow_dispatch:

jobs:
  release-patch:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release')
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - uses: actions/cache@v3
        id: cached-poetry
        with:
          path: ~/.local
          key: poetry-0

      - uses: snok/install-poetry@v1
        if: steps.cached-poetry.outputs.cache-hit != 'true'

      - name: Bump patch version
        id: bump-version
        run: echo "VERSION=$(poetry version --short patch)" >> $GITHUB_OUTPUT

      - name: Create release tag
        uses: EndBug/add-and-commit@v9
        with:
          tag: "v${{ steps.bump-version.outputs.VERSION }}"
          default_author: github_actions
          message: Bump patch version
          add: pyproject.toml
