name: Create release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    concurrency:
      group: create-release
    permissions:
      contents: write
    outputs:
      version: ${{ steps.semrel.outputs.version }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 100
          fetch-tags: true

      - name: Create GitHub release
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: 'emojis=true'

  build-python-wheel:
    uses: ./.github/workflows/wheel_build.yml
    needs: create-release

  upload-assets:
    runs-on: ubuntu-latest
    needs: [create-release, build-python-wheel]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v6
        with:
          name: python-wheel

      - name: Upload release assets
        run: gh release upload "$TAG_NAME" dist/*.whl remote_api.json
        env:
          TAG_NAME: 'v${{ needs.create-release.outputs.version }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docker-image:
    uses: ./.github/workflows/docker_build.yml
    needs: [create-release, build-python-wheel]
    permissions:
      packages: write
    with:
      tags: |
        ghcr.io/kmolski/acme-bot:v${{ needs.create-release.outputs.version }}
        ghcr.io/kmolski/acme-bot:latest
