name: GitHub release minor version

on:
  workflow_dispatch:

jobs:
  release-minor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/cache@v3
        id: cached-poetry
        with:
          path: |
            ~/.local
            ~/.cache/pypoetry/virtualenvs
          key: poetry-0

      - uses: snok/install-poetry@v1
        if: steps.cached-poetry.outputs.cache-hit != 'true'

      - name: Bump minor version
        id: bump-version
        run: echo "VERSION=$(poetry version --short minor)" >> $GITHUB_OUTPUT

      - name: Generate release branch suffix
        id: generate-branch-name
        run: echo "BRANCH=$(echo '${{ steps.bump-version.outputs.VERSION }}' | sed 's/\.[0-9]*$/.x/')" >> $GITHUB_OUTPUT

      - name: Create release branch & tag
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: "release/${{ steps.generate-branch-name.outputs.BRANCH }}"
          tag: "v${{ steps.bump-version.outputs.VERSION }}"
          default_author: github_actions
          message: Bump minor version
          add: pyproject.toml
